version: '3.5'

services:
  backend:
    image: 'allless/continuum:latest'
    networks:
      - continuum-network
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    entrypoint:
      - bash
      - /opt/continuum/bin/start_backend.sh

networks:
  continuum-network:
    external: true
