version: '3'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379'
    networks:
      - continuum
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

  data_frontend:
    image: 'allless/continuum:0.1'
    ports:
      - '1339:1339'
      - '7001:7001'
    networks:
      - continuum
    depends_on:
      - redis
    entrypoint:
      - /opt/continuum/debug/src/frontends/data_frontend
      - --redis_ip
      - redis

  management_frontend:
    image: 'allless/continuum:0.1'
    ports:
      - '1338:1338'
    networks:
      - continuum
    depends_on:
      - redis
    entrypoint:
      - /opt/continuum/debug/src/management/management_frontend
      - --redis_ip
      - redis

  backend:
    image: 'allless/continuum:0.1'
    networks:
      - continuum
    depends_on:
      - data_frontend
    entrypoint:
      - bash
      - /opt/continuum/bin/start_backend.sh

networks:
  continuum:

