# coding: utf-8

SOCKET_POLLING_TIMEOUT_MILLIS = 5000
SOCKET_ACTIVITY_TIMEOUT_MILLIS = 30000

STATE_DESTROYED = 0
STATE_IDLE = 1
STATE_RECEIVING = 2
STATE_RECEIVABLE = 3

REQUEST_TYPE_START_RETRAIN = 0

MESSAGE_TYPE_BACKEND_HAERTBEAT = 3
MESSAGE_TYPE_BACKEND_METADATA = 4
MESSAGE_TYPE_START_RETRAIN = 5
MESSAGE_TYPE_RETRAIN_STARTED = 6
MESSAGE_TYPE_RETRAIN_ENDED = 7

BACKEND_HEARTBEAT_TYPE_KEEPALIVE = 0
BACKEND_HEARTBEAT_TYPE_REQUEST_METADATA = 1

REDIS_HOST = 'localhost'
REDIS_PORT = 6379

REDIS_STATE_DB_NUM = 1
REDIS_MODEL_DB_NUM = 2
REDIS_CONTAINER_DB_NUM = 3
REDIS_RESOURCE_DB_NUM = 4
REDIS_APPLICATION_DB_NUM = 5
REDIS_METADATA_DB_NUM = 6
REDIS_APP_MODEL_LINKS_DB_NUM = 7
REDIS_BACKEND_DB_NUM = 8
REDIS_APP_BACKEND_LINK_DB_NUM = 9
REDIS_RETRAIN_DATA_DB = 10
REDIS_APP_DATA_LINK_DB = 11

ITEM_DELIMITER = ','
